[versions]
micronaut-docs = "2.0.0"
micronaut = "4.0.0-M2"
micronaut-test = "4.0.0-M2"
groovy = "4.0.11"
spock = "2.3-groovy-4.0"

graal-svm = "22.3.2"
kotlin = '1.8.20'
shadow = '7.1.2'
micronaut-gradle-plugin = "4.0.0-M1"

micronaut-kotlin = "4.0.0-M1"
micronaut-security = "4.0.0-M2"
micronaut-serde = "2.0.0-M1"

managed-graphql-java = "16.2"
managed-graphql-java-extended-scalars = "1.1.0"
managed-graphql-java-tools = "13.0.2"
managed-graphql-spqr = "0.11.2"

[libraries]
graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }

micronaut-kotlin = { module = "io.micronaut.kotlin:micronaut-kotlin-bom", version.ref = "micronaut-kotlin" }
micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }

managed-graphql-java = { module = 'com.graphql-java:graphql-java', version.ref = 'managed-graphql-java' }
managed-graphql-java-extended-scalars = { module = 'com.graphql-java:graphql-java-extended-scalars', version.ref = 'managed-graphql-java-extended-scalars' }
managed-graphql-java-tools = { module = 'com.graphql-java-kickstart:graphql-java-tools', version.ref = 'managed-graphql-java-tools' }
managed-graphql-spqr = { module = 'io.leangen.graphql:spqr', version.ref = 'managed-graphql-spqr' }

#plugins
kotlin-gradle-plugin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
kotlin-gradle-allopen = { module = 'org.jetbrains.kotlin:kotlin-allopen', version.ref = 'kotlin' }
shadow-plugin = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }
micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref="micronaut-gradle-plugin" }
